[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["echo 'Skipping build - using JavaScript directly'"]

[start]
cmd = "node index.js"
