name: build-and-test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ "${{ matrix.project }}" = "frontend" ]; then
            cd frontend && npm install
          else
            cd backend && npm install
          fi

      - name: Run build
        run: |
          if [ "${{ matrix.project }}" = "frontend" ]; then
            cd frontend && npm run build
          else
            cd backend && npm run build
          fi

      - name: Run tests (if available)
        run: |
          if [ "${{ matrix.project }}" = "frontend" ]; then
            cd frontend && npm run test || echo "No tests configured"
          else
            cd backend && npm run test || echo "No tests configured"
          fi
        continue-on-error: true

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.modified, 'frontend/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd frontend
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NEXT_PUBLIC_API_BASE_URL: https://medmsg-railway-production.up.railway.app
