name: infra-lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'infra/**'
  push:
    paths:
      - 'infra/**'

jobs:
  bicep-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Bicep build
        uses: azure/cli@v2
        with:
          inlineScript: az bicep build --file infra/main.bicep
