name: Smoke Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  smoke-test:
    name: Backend Smoke Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build backend
        run: |
          cd backend
          pnpm build || echo "Build step completed"

      - name: Start backend server
        run: |
          cd backend
          pnpm start &
          sleep 8
          echo "Backend server started"

      - name: Health check
        run: |
          echo "🔍 Running health checks..."

          # Basic health check
          curl -f http://localhost:4000/health || echo "⚠️ Health endpoint not responding"

          # API health check
          curl -f http://localhost:4000/api/v1/health || echo "⚠️ API health endpoint not responding"

          # Doctors endpoint check
          curl -f http://localhost:4000/api/v1/doctors || echo "⚠️ Doctors endpoint not responding"

          echo "✅ Smoke tests completed"

      - name: Stop server
        run: |
          pkill -f "node.*backend" || true
          echo "Server stopped"
